//! Reads of the upstream projection tables: `usage_ledger`,
//! `sessions.message_count` / `usage_payload`, `branch_entries` /
//! `branch_meta`.
//!
//! Everything here runs against `fixtures/ts_recorded.sqlite`, which is
//! generated by `scripts/make-ts-fixture.mjs` through the verbatim
//! upstream DDL. That fixture carries three ledger rows (one of them an
//! `adjustment`) and a two-branch index: a linear root branch plus a
//! divergent one that forks at the newest compaction boundary and re-owns
//! the post-compaction tail. The assertions are field-by-field on
//! purpose — the point of this suite is to pin the *upstream* shape, not
//! to confirm that the reader can read what it just wrote.

use std::path::{Path, PathBuf};

use pi_protocol::Usage;
use pi_session::{
    BranchEntry, BranchMeta, BranchOrder, BranchScan, SchemaLayout, SessionReader, UsageOrder,
    UsageScan,
};
use rusqlite::Connection;

mod common;

use common::{fresh_dir, write_rust_legacy_fixture};

const SESSION_ID: &str = "ts-recorded-fixture";

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/ts_recorded.sqlite")
}

fn open_fixture() -> SessionReader {
    SessionReader::open(fixture_path()).expect("open fixture")
}

/// Copy the committed fixture somewhere writable so a test can corrupt
/// the `sessions` projection without touching the shared file.
fn mutable_copy(label: &str) -> (PathBuf, PathBuf) {
    let dir = fresh_dir(label);
    let path = dir.join("ts_recorded.sqlite");
    std::fs::copy(fixture_path(), &path).expect("copy fixture");
    (dir, path)
}

fn usage(input: u32, output: u32, cache_read: u32, cache_write: u32, total: u32) -> Usage {
    Usage {
        input,
        output,
        cache_read,
        cache_write,
        total,
    }
}

/// The ledger sum the fixture's cache also carries.
fn fixture_total_usage() -> Usage {
    usage(225, 33, 5, 2, 261)
}

// ---------------------------------------------------------------------
// usage_ledger
// ---------------------------------------------------------------------

#[test]
fn usage_ledger_rows_decode_field_for_field() {
    let reader = open_fixture();
    let rows = reader.iter_usage(SESSION_ID).expect("iter_usage");
    assert_eq!(rows.len(), 3, "fixture holds three ledger rows");

    // u1: per-response usage attributed to the assistant entry.
    assert_eq!(rows[0].id, "u1-assistant");
    assert_eq!(
        rows[0].seq, 7,
        "seq comes from the shared entry/usage counter"
    );
    assert_eq!(rows[0].entry_id.as_deref(), Some("e2-assistant"));
    assert!(!rows[0].adjustment);
    assert_eq!(rows[0].usage, usage(120, 8, 4, 0, 128));
    assert_eq!(rows[0].details, None);

    // u2: per-response usage attributed to the compaction entry.
    assert_eq!(rows[1].id, "u2-compaction");
    assert_eq!(rows[1].seq, 8);
    assert_eq!(rows[1].entry_id.as_deref(), Some("e4-compaction"));
    assert!(!rows[1].adjustment);
    assert_eq!(rows[1].usage, usage(100, 20, 0, 0, 120));

    // u3: harness-recorded adjustment — an `adjustment` flag and no
    // attribution, but still a usage row.
    assert_eq!(rows[2].id, "u3-hook-adjustment");
    assert_eq!(rows[2].seq, 9);
    assert_eq!(rows[2].entry_id, None);
    assert!(rows[2].adjustment);
    assert_eq!(rows[2].usage, usage(5, 5, 1, 2, 13));
    let details = rows[2]
        .details
        .as_ref()
        .expect("adjustment carries details");
    assert_eq!(details["reason"], "hook");
    assert_eq!(details["source"], "fixture");
}

#[test]
fn usage_lookup_by_entry_and_totals_include_adjustments() {
    let reader = open_fixture();

    // Reverse lookup by `entry_id`.
    let attributed = reader
        .usage_for_entry(SESSION_ID, "e2-assistant")
        .expect("usage_for_entry");
    assert_eq!(attributed.len(), 1);
    assert_eq!(attributed[0].id, "u1-assistant");

    // An entry with no ledger row returns an empty list, not an error.
    assert!(reader
        .usage_for_entry(SESSION_ID, "e1-user")
        .expect("usage_for_entry")
        .is_empty());

    // The adjustment row is unattributed, so it is reachable only through
    // the full scan — and it counts into the total.
    let totals = reader.usage_totals(SESSION_ID).expect("usage_totals");
    assert_eq!(totals, fixture_total_usage());
    assert_eq!(
        totals,
        pi_session::sum_usage(
            reader
                .iter_usage(SESSION_ID)
                .unwrap()
                .into_iter()
                .map(|r| r.usage)
        ),
        "usage_totals must be exactly the fold of the ledger rows"
    );
}

#[test]
fn a_ledger_row_can_be_joined_back_to_its_entry() {
    let reader = open_fixture();
    let rows = reader.iter_usage(SESSION_ID).expect("iter_usage");

    let entry = rows[0]
        .entry(&reader, SESSION_ID)
        .expect("entry")
        .expect("u1 points at e2-assistant");
    assert_eq!(entry.entry_id.as_deref(), Some("e2-assistant"));
    assert_eq!(entry.seq, 2);
    assert!(matches!(
        entry.entry,
        pi_protocol::SessionEntry::AssistantMessage(_)
    ));

    // Unattributed rows (the adjustment) have nothing to join to.
    assert!(rows[2].entry(&reader, SESSION_ID).expect("entry").is_none());
}

#[test]
fn usage_scan_supports_range_order_and_limit() {
    let reader = open_fixture();

    let ids = |scan: &UsageScan| -> Vec<String> {
        reader
            .scan_usage(SESSION_ID, scan)
            .expect("scan_usage")
            .into_iter()
            .map(|row| row.id)
            .collect()
    };

    // Descending order.
    assert_eq!(
        ids(&UsageScan {
            order: UsageOrder::Desc,
            ..UsageScan::default()
        }),
        vec!["u3-hook-adjustment", "u2-compaction", "u1-assistant"]
    );

    // Inclusive `from_seq` / `to_seq` bounds (upstream `seq >= from`,
    // `seq <= to`).
    assert_eq!(
        ids(&UsageScan {
            from_seq: Some(8),
            to_seq: Some(8),
            ..UsageScan::default()
        }),
        vec!["u2-compaction"]
    );

    // Limit applies after ordering.
    assert_eq!(
        ids(&UsageScan {
            order: UsageOrder::Desc,
            limit: Some(2),
            ..UsageScan::default()
        }),
        vec!["u3-hook-adjustment", "u2-compaction"]
    );

    assert!(ids(&UsageScan {
        limit: Some(0),
        ..UsageScan::default()
    })
    .is_empty());

    // An unknown session has an empty ledger, not an error.
    assert!(reader.iter_usage("nope").expect("iter_usage").is_empty());
}

// ---------------------------------------------------------------------
// session stats
// ---------------------------------------------------------------------

#[test]
fn session_stats_read_the_cache_and_agree_with_the_recompute() {
    let reader = open_fixture();

    let cached = reader
        .session_stats(SESSION_ID)
        .expect("session_stats")
        .expect("fixture has a sessions row");
    assert_eq!(cached.message_count, 4, "e1..e3 + the fork entry");
    assert_eq!(cached.usage, fixture_total_usage());

    let recomputed = reader
        .recompute_stats(SESSION_ID)
        .expect("recompute_stats")
        .expect("fixture has a sessions row");
    assert_eq!(recomputed, cached);

    let check = reader
        .verify_stats(SESSION_ID)
        .expect("verify_stats")
        .expect("fixture has a sessions row");
    assert!(check.is_consistent(), "{check:?}");

    // Unknown sessions are `None` everywhere, never a fabricated zero.
    assert_eq!(reader.session_stats("nope").expect("session_stats"), None);
    assert_eq!(reader.recompute_stats("nope").expect("recompute"), None);
    assert_eq!(reader.verify_stats("nope").expect("verify"), None);
}

#[test]
fn recompute_counts_only_message_entries() {
    let reader = open_fixture();
    // The fixture has seven entries but only four `type = "message"` rows;
    // compaction / custom / branch_summary must not be counted, which is
    // exactly what upstream `incrementMessageCount` does.
    assert_eq!(reader.count_entries(SESSION_ID).unwrap(), 7);
    assert_eq!(
        reader
            .recompute_stats(SESSION_ID)
            .unwrap()
            .unwrap()
            .message_count,
        4
    );
}

#[test]
fn a_stale_sessions_cache_is_reported_instead_of_trusted() {
    let (_dir, path) = mutable_copy("stale-stats");
    {
        let conn = Connection::open(&path).expect("open copy");
        // Simulate a crash between the durable write and the projection
        // update: the ledger has the adjustment row, the cache does not
        // (and the message count lags too).
        conn.execute(
            "UPDATE sessions SET message_count = 5, usage_payload = ?1 WHERE id = ?2",
            rusqlite::params![
                serde_json::json!({
                    "input": 220,
                    "output": 28,
                    "cacheRead": 4,
                    "cacheWrite": 0,
                    "totalTokens": 248,
                    "cost": {"input": 0.0, "output": 0.0, "cacheRead": 0.0, "cacheWrite": 0.0, "total": 0.0}
                })
                .to_string(),
                SESSION_ID
            ],
        )
        .expect("corrupt the cache");
    }

    let reader = SessionReader::open(&path).expect("open fixture copy");
    let check = reader
        .verify_stats(SESSION_ID)
        .expect("verify_stats")
        .expect("has a sessions row");
    assert!(!check.is_consistent());
    assert_eq!(check.cached.message_count, 5);
    assert_eq!(check.cached.usage, usage(220, 28, 4, 0, 248));
    assert_eq!(check.recomputed.message_count, 4);
    assert_eq!(check.recomputed.usage, fixture_total_usage());

    // The cache read still returns exactly what the `sessions` row says —
    // the drift is surfaced, but `session_stats` keeps its documented
    // "cached" contract; callers that need a guarantee call `verify_stats`.
    assert_eq!(
        reader.session_stats(SESSION_ID).unwrap().unwrap(),
        check.cached
    );
}

// ---------------------------------------------------------------------
// branch index
// ---------------------------------------------------------------------

#[test]
fn branch_meta_matches_the_upstream_index() {
    let reader = open_fixture();
    let meta = reader.branch_meta(SESSION_ID).expect("branch_meta");
    assert_eq!(
        meta,
        vec![
            BranchMeta {
                branch_id: "e1-user".into(),
                tip_entry_id: "e6-branch-summary".into(),
                tip_seq: 6,
                base_branch_id: None,
                base_seq: None,
            },
            BranchMeta {
                branch_id: "e7-fork".into(),
                tip_entry_id: "e7-fork".into(),
                tip_seq: 10,
                base_branch_id: Some("e1-user".into()),
                base_seq: Some(4),
            },
        ]
    );

    assert_eq!(
        reader
            .branch_meta_for(SESSION_ID, "e7-fork")
            .expect("branch_meta_for"),
        Some(meta[1].clone())
    );
    assert_eq!(
        reader
            .branch_meta_for(SESSION_ID, "nope")
            .expect("branch_meta_for"),
        None
    );
}

#[test]
fn branch_entries_keep_the_copied_tail_per_branch() {
    let reader = open_fixture();

    let root = reader
        .branch_entries(SESSION_ID, "e1-user")
        .expect("branch_entries");
    assert_eq!(
        root,
        vec![
            BranchEntry {
                branch_id: "e1-user".into(),
                entry_id: "e1-user".into(),
                entry_seq: 1,
                entry_type: "message".into(),
            },
            BranchEntry {
                branch_id: "e1-user".into(),
                entry_id: "e2-assistant".into(),
                entry_seq: 2,
                entry_type: "message".into(),
            },
            BranchEntry {
                branch_id: "e1-user".into(),
                entry_id: "e3-toolresult".into(),
                entry_seq: 3,
                entry_type: "message".into(),
            },
            BranchEntry {
                branch_id: "e1-user".into(),
                entry_id: "e4-compaction".into(),
                entry_seq: 4,
                entry_type: "compaction".into(),
            },
            BranchEntry {
                branch_id: "e1-user".into(),
                entry_id: "e5-custom".into(),
                entry_seq: 5,
                entry_type: "custom".into(),
            },
            BranchEntry {
                branch_id: "e1-user".into(),
                entry_id: "e6-branch-summary".into(),
                entry_seq: 6,
                entry_type: "branch_summary".into(),
            },
        ]
    );

    // The divergent branch re-owns the post-compaction tail (e5, e6) and
    // then extends it with the fork entry.
    let fork = reader
        .branch_entries(SESSION_ID, "e7-fork")
        .expect("branch_entries");
    assert_eq!(fork.len(), 3);
    assert_eq!(
        fork.iter().map(|row| &row.entry_id).collect::<Vec<_>>(),
        vec!["e5-custom", "e6-branch-summary", "e7-fork"]
    );
    assert_eq!(
        fork.iter().map(|row| row.entry_seq).collect::<Vec<_>>(),
        vec![5, 6, 10]
    );

    assert!(reader
        .branch_entries(SESSION_ID, "missing")
        .expect("branch_entries")
        .is_empty());
}

#[test]
fn branch_scan_walks_segments_in_both_directions() {
    let reader = open_fixture();

    let ids = |scan: &BranchScan| -> Vec<String> {
        reader
            .scan_branch(SESSION_ID, scan)
            .expect("scan_branch")
            .into_iter()
            .map(|entry| entry.entry_id.expect("upstream entries carry ids"))
            .collect()
    };

    // `start` is the anchor the walk ends at (upstream resolves the
    // branch membership from that entry), so starting at the root entry
    // yields just that entry.
    assert_eq!(ids(&BranchScan::from("e1-user")), vec!["e1-user"]);
    assert_eq!(
        ids(&BranchScan {
            order: BranchOrder::OldestFirst,
            ..BranchScan::from("e1-user")
        }),
        vec!["e1-user"]
    );

    // The fork has two segments: its own tail, then the base branch up to
    // the compaction boundary. `e5`/`e6` are only returned once — from the
    // fork segment, which is the newer one.
    assert_eq!(
        ids(&BranchScan {
            order: BranchOrder::OldestFirst,
            ..BranchScan::from("e7-fork")
        }),
        vec![
            "e1-user",
            "e2-assistant",
            "e3-toolresult",
            "e4-compaction",
            "e5-custom",
            "e6-branch-summary",
            "e7-fork",
        ]
    );
    assert_eq!(
        ids(&BranchScan::from("e7-fork")),
        vec![
            "e7-fork",
            "e6-branch-summary",
            "e5-custom",
            "e4-compaction",
            "e3-toolresult",
            "e2-assistant",
            "e1-user",
        ]
    );

    // `e6` belongs to both branches; the membership query picks the branch
    // with the newest tip (the fork), which is why the root branch's full
    // walk and the fork's walk agree once the mark is below the fork.
    assert_eq!(
        ids(&BranchScan {
            order: BranchOrder::OldestFirst,
            ..BranchScan::from("e6-branch-summary")
        }),
        vec![
            "e1-user",
            "e2-assistant",
            "e3-toolresult",
            "e4-compaction",
            "e5-custom",
            "e6-branch-summary",
        ]
    );

    // Scans decode; they do not hand back raw rows.
    let entries = reader
        .scan_branch(SESSION_ID, &BranchScan::from("e7-fork"))
        .expect("scan_branch");
    assert_eq!(entries[0].seq, 10);
    assert_eq!(entries[0].entry_id.as_deref(), Some("e7-fork"));
    assert_eq!(entries[0].type_, "message");
    assert!(matches!(
        entries[0].entry,
        pi_protocol::SessionEntry::UserMessage(_)
    ));
    assert_eq!(entries[3].type_, "compaction");
    assert!(matches!(
        entries[3].entry,
        pi_protocol::SessionEntry::Compaction { .. }
    ));

    // An entry that is not in the branch index is a corrupt index, and
    // upstream throws for it too.
    let err = reader
        .scan_branch(SESSION_ID, &BranchScan::from("no-such-entry"))
        .unwrap_err();
    assert!(
        err.to_string().contains("branch cache missing entry"),
        "unexpected error: {err}"
    );
}

#[test]
fn branch_scan_applies_type_cursor_limit_and_stop() {
    let reader = open_fixture();

    let ids = |scan: &BranchScan| -> Vec<String> {
        reader
            .scan_branch(SESSION_ID, scan)
            .expect("scan_branch")
            .into_iter()
            .map(|entry| entry.entry_id.expect("upstream entries carry ids"))
            .collect()
    };

    // Limit stops the walk once the budget is spent (oldest first, so the
    // oldest entries win).
    assert_eq!(
        ids(&BranchScan {
            order: BranchOrder::OldestFirst,
            limit: Some(3),
            ..BranchScan::from("e7-fork")
        }),
        vec!["e1-user", "e2-assistant", "e3-toolresult"]
    );
    assert!(ids(&BranchScan {
        limit: Some(0),
        ..BranchScan::from("e7-fork")
    })
    .is_empty());

    // `type_` filters on `branch_entries.entry_type`; only the fork branch
    // has a `custom` entry.
    assert_eq!(
        ids(&BranchScan {
            order: BranchOrder::OldestFirst,
            type_: Some("custom".into()),
            ..BranchScan::from("e7-fork")
        }),
        vec!["e5-custom"]
    );

    // `custom_type` filters on `entries.custom_type`.
    assert_eq!(
        ids(&BranchScan {
            order: BranchOrder::OldestFirst,
            custom_type: Some("ts-fixture:marker".into()),
            ..BranchScan::from("e7-fork")
        }),
        vec!["e5-custom"]
    );

    // `cursor` is exclusive and applied per segment (upstream resumes a
    // paged scan that way).
    assert_eq!(
        ids(&BranchScan {
            order: BranchOrder::OldestFirst,
            cursor: Some(3),
            ..BranchScan::from("e7-fork")
        }),
        vec!["e4-compaction", "e5-custom", "e6-branch-summary", "e7-fork",]
    );

    // `stop_at_type` is inclusive and cuts the walk at the newest matching
    // entry of the first segment that has one.
    assert_eq!(
        ids(&BranchScan {
            stop_at_type: Some("compaction".into()),
            ..BranchScan::from("e7-fork")
        }),
        vec!["e7-fork", "e6-branch-summary", "e5-custom", "e4-compaction",]
    );

    // `stop_at_id` behaves the same and, walking newest first, still
    // includes the entries between the tip and the stop entry.
    assert_eq!(
        ids(&BranchScan {
            stop_at_id: Some("e3-toolresult".into()),
            ..BranchScan::from("e7-fork")
        }),
        vec![
            "e7-fork",
            "e6-branch-summary",
            "e5-custom",
            "e4-compaction",
            "e3-toolresult",
        ]
    );
}

// ---------------------------------------------------------------------
// legacy layout
// ---------------------------------------------------------------------

#[test]
fn projection_reads_reject_the_rust_legacy_layout() {
    let dir: PathBuf = fresh_dir("usage-branch-legacy");
    let path = dir.join("legacy.sqlite");
    write_rust_legacy_fixture(&path, "legacy", "0.1.0", &[]);

    let reader = SessionReader::open(&path).expect("open legacy");
    assert_eq!(reader.layout(), SchemaLayout::RustLegacy);

    // The legacy layout has none of these tables; reading must fail loudly
    // instead of looking like an empty session.
    for err in [
        reader.iter_usage("legacy").unwrap_err(),
        reader.session_stats("legacy").unwrap_err(),
        reader.recompute_stats("legacy").unwrap_err(),
        reader.branch_meta("legacy").unwrap_err(),
        reader
            .scan_branch("legacy", &BranchScan::from("x"))
            .unwrap_err(),
    ] {
        assert!(
            matches!(err, pi_session::SessionError::Other(_)),
            "expected a layout error, got {err:?}"
        );
        assert!(
            err.to_string().contains("upstream v4 layout"),
            "unexpected error: {err}"
        );
    }
}

/// The fixture path helper must not silently accept a missing file.
#[test]
fn the_fixture_exists() {
    assert!(Path::new(&fixture_path()).exists());
}
